services:

  mysql:
    image: mysql:8.0
    container_name: chess_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess_api
      MYSQL_USER: chess_user
      MYSQL_PASSWORD: chess_pass
    ports:
      - "3307:3306"
    volumes:
      - chess_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: chess-stat-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./chess-stat-front
    container_name: chess-stat-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

volumes:
  chess_data: