spring:
  application:
    name: chess-api

  datasource:
    url: jdbc:mysql://localhost:3307/chess_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: chess_user
    password: chess_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 3000

logging:
  level:
    com.chess: DEBUG
    org.hibernate.SQL: WARN
